CREATE TABLE IF NOT EXISTS songs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `name` VARCHAR(100) UNIQUE,
    `artist` VARCHAR(100),
    `genre` VARCHAR(100),
    `album` VARCHAR(100),
    `year` INT,
    `durSec` INT,
    `artwork` VARCHAR(300)
    );